# Generated by Django 5.1.4 on 2026-03-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgen', '0002_studynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='style',
            field=models.CharField(default='detailed', max_length=20),
        ),
    ]
